packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'packages/locales/*'
  - 'apps/*'
  - 'examples/*'
  - 'plugins/*'  
  - 'shells/*'  
  - 'internal/vite-config'
  # exclude packages that are inside test directories
  - '!**/test/**'
