packages:
  # all packages in direct subdirs of packages/
  - 'internal/*'
  - 'packages/*'
  - 'packages/locales/*'
  - 'plugins/*'  
  - 'shells/*'  
  - 'examples/*'  
  - 'apps/*'
  - 'apps/nop-site/packages/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
